const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const c=vm.createContext({pct:x=>x==null?'—':(x*100).toFixed(2)+'%',escapeHtml:x=>String(x??''),console});
vm.runInContext(fs.readFileSync('ui/live-portfolio.js','utf8'),c);
const positions=[{ticker:'sold',quantity:0,target_weight:0},{ticker:'held',quantity:3,target_weight:0},{ticker:'target',quantity:0,target_weight:.1},{ticker:'small',quantity:1e-12,target_weight:0}];
c.positions=positions;
assert.deepEqual(Array.from(vm.runInContext('currentPositionRows(positions)',c),r=>r.ticker),['held','target','small']);
assert.equal(positions.length,4);
c.detail={portfolio:{id:'test'},position_history:Array.from({length:25},(_,i)=>({date:'2026-09-22',ticker:'ETF'+i,name:'华夏',action:i%2?'SELL':'BUY',source:'PAPER',quantity:i,target_weight:.1,weight:.1,price:1,position_value:i}))};
let html=vm.runInContext('positionHistoryBody(detail)',c);
assert.match(html,/Showing 1–10 of 25/);assert.equal((html.match(/<tr>/g)||[]).length,11);
html=vm.runInContext('historyView("test").page=2;positionHistoryBody(detail)',c);
assert.match(html,/Showing 21–25 of 25/);
html=vm.runInContext('Object.assign(historyView("test"),{field:"action",query:"sell",page:0});positionHistoryBody(detail)',c);
assert.match(html,/Showing 1–10 of 12/);assert.doesNotMatch(html,/<td>BUY<\/td>/);
assert.equal(vm.runInContext('filteredPositionHistory(detail.position_history,{field:"name",query:"华夏"}).length',c),25);
assert.equal(vm.runInContext('filteredPositionHistory(detail.position_history,{field:"target_weight",query:"10.00%"}).length',c),25);
html=vm.runInContext('Object.assign(historyView("test"),{query:"missing",page:4});positionHistoryBody(detail)',c);
assert.match(html,/Showing 0–0 of 0/);assert.match(html,/No matching/);
assert.equal(c.detail.position_history.length,25);
assert.equal(vm.runInContext('historyView("other").query',c),'');
console.log('PASS: exited rows hidden, holdings/targets retained, 10-row pages, filtering before pagination, Chinese text, empty results, portfolio isolation, original data preserved');
