const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require(process.env.MOMENTUM_PLAYWRIGHT_MODULE||'playwright');
const [base,root,python]=process.argv.slice(2);
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.MOMENTUM_BROWSER_CHANNEL?{channel:process.env.MOMENTUM_BROWSER_CHANNEL}:{})});
 try{
  const page=await browser.newPage({acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/test-workspace');await page.locator('[data-page="manager"]').first().click();assert.equal(await page.locator('#integrityDashboard').count(),1);
  await page.locator('#wsCheck').click();await page.getByText('Click received; starting validation.').waitFor();
  await page.waitForFunction(()=>document.querySelector('#wsSummary')?.textContent.includes('review groups'),{timeout:45000});
  assert.match(await page.locator('#wsPager').innerText(),/page 1 \/ 3/);
  assert.equal(await page.locator('.wsGroup').count(),50);
  assert.match(await page.locator('#wsSummary').innerText(),/Blocked by:/);
  const notices=page.locator('.wsGroup').filter({hasText:'Dataset-wide'});
  assert.ok(await notices.count()>0);
  assert.equal(await notices.first().locator('.wsSelect').isDisabled(),true);
  assert.equal(await page.locator('#wsRepair').isDisabled(),true);
  await page.locator('.wsSelect:not(:disabled)').first().check();
  const selectedCount=Number((await page.locator('#wsSelectedCount').innerText()).match(/^\d+/)[0]);
  assert.ok(selectedCount>=1);
  assert.equal(await page.locator('#wsRepair').isEnabled(),true);
  await page.locator('#wsRepair').click();
  await page.getByText('Click received; planning '+selectedCount+' selected finding'+(selectedCount===1?'':'s')+'.').waitFor();
  await page.waitForFunction(()=>document.querySelector('#wsOperation')?.textContent.includes('Repair · COMPLETED_WITH_WARNINGS'),{timeout:45000});
  assert.match(await page.locator('#wsPreview').innerText(),/Committed: false/);
  await page.locator('#wsClear').click();
  await page.locator('#wsNext').click();await page.getByText('page 2 / 3').waitFor();assert.ok(await page.locator('.wsGroup').count()>0);
  await page.locator('#wsFirst').click();await page.getByText('page 1 / 3').waitFor();
  const downloadPromise=page.waitForEvent('download');await page.locator('#wsExportPage').click();
  await page.getByText('Preparing workbook.').waitFor();const download=await downloadPromise;
  const pageWorkbook=path.join(root,'page.xlsx');await download.saveAs(pageWorkbook);
  assert.equal(Number(execFileSync(python,['-c',"from openpyxl import load_workbook;import sys;print(load_workbook(sys.argv[1],read_only=True)['Review'].max_row)",pageWorkbook],{encoding:'utf8'}).trim()),51);
  await page.locator('#wsFilters [data-key="ticker"]').fill('A');await page.waitForFunction(()=>document.querySelector('#wsPager')?.textContent.includes('of 1 groups'));
  const filteredPending=page.waitForEvent('download');await page.locator('#wsExportFiltered').click();const filtered=await filteredPending;
  const filteredWorkbook=path.join(root,'filtered.xlsx');await filtered.saveAs(filteredWorkbook);
  assert.equal(Number(execFileSync(python,['-c',"from openpyxl import load_workbook;import sys;print(load_workbook(sys.argv[1],read_only=True)['Review'].max_row)",filteredWorkbook],{encoding:'utf8'}).trim()),2);
  await page.locator('#wsFilters [data-key="ticker"]').fill('');await page.waitForFunction(()=>document.querySelector('#wsPager')?.textContent.includes('of 123 groups'));
  const allPending=page.waitForEvent('download');await page.locator('#wsExportAll').click();const allDownload=await allPending;
  const workbook=path.join(root,'review.xlsx');await allDownload.saveAs(workbook);
  const info=execFileSync(python,['-c',"from openpyxl import load_workbook;import sys;w=load_workbook(sys.argv[1]);s=w['Review'];print(s.max_row);row=next(r for r in s.iter_rows(min_row=2) if r[5].value=='A' and 'raw_price' in r[8].value);row[17].value='已核对，accepted gap';row[13].value='display text changed harmlessly';w.save(sys.argv[1])",workbook],{encoding:'utf8'}).trim();
  assert.equal(Number(info),124);
  await page.locator('#wsFile').setInputFiles(workbook);await page.locator('#wsUploadButton').click();
  await page.getByText('No decisions can be applied because no valid actionable rows exist.').waitFor({timeout:45000});
  assert.equal(await page.locator('#wsApply').isDisabled(),true);
  execFileSync(python,['-c',"from openpyxl import load_workbook;import sys;w=load_workbook(sys.argv[1]);s=w['Review'];row=next(r for r in s.iter_rows(min_row=2) if r[5].value=='A' and 'raw_price' in r[8].value);row[16].value='confirm';w.save(sys.argv[1])",workbook]);
  await page.locator('#wsFile').setInputFiles(workbook);await page.locator('#wsUploadButton').click();
  await page.waitForFunction(()=>document.querySelector('#wsPreview')?.textContent.includes('1 valid'),{timeout:45000});
  assert.match(await page.locator('#wsPreview').innerText(),/1 valid/);assert.match(await page.locator('#wsPreview').innerText(),/已核对/);
  await page.locator('#wsPreviewNext').click();await page.waitForFunction(()=>document.querySelector('#wsPreview')?.textContent.includes('51–100 of 123'));
  const ack=path.join(root,'completeness_acknowledgments.json');assert.equal(fs.existsSync(ack),false);
  await page.locator('#wsApply').click();await page.waitForFunction(()=>document.querySelector('#wsOperation')?.textContent.includes('Review apply · COMPLETED'),{timeout:45000});
  const items=JSON.parse(fs.readFileSync(ack,'utf8'));assert.equal(items.length,2);assert.equal(items[0].explanation,items[1].explanation);assert.equal(items[1].inherited_from,items[0].confirmation_id);
  await page.reload();await page.locator('[data-page="manager"]').first().click();await page.locator('#wsCheck').click();await page.waitForFunction(()=>document.querySelector('#wsSummary')?.textContent.includes('review groups'),{timeout:45000});
  await page.locator('#wsFilters [data-key="status"]').selectOption('CONFIRMED');
  await page.waitForFunction(()=>document.querySelector('#wsPager')?.textContent.includes('of 1 groups'),{timeout:20000});
  assert.match(await page.locator('.wsGroup table').first().textContent(),/adjusted_price/);
  await page.screenshot({path:path.resolve('diagnostics/integrity_workspace_verified.png'),fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: temporary browser UI check, export, 50-group pagination, upload preview, apply, inheritance, reload, grouped confirmation.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
